multivendor/core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.frontpage, name = 'frontpage'),
    path('about/', views.about, name = 'about')
]

multivendor/multivendor/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('robots.txt', TemplateView.as_view(template_name='core/robots.txt', content_type='text/plain')),
    path('', include('userprofile.urls')),
    path('', include('core.urls'), name = 'core'),
    path('', include('store.urls')),    

] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

multivendor/core/models.py
from django.db import models

# Create your models here.

multivendor/core/views.py
from django.shortcuts import render

from store.models import Product

# Create your views here.
def frontpage(request):
    products = Product.objects.filter(status = Product.ACTIVE)[0:6]
    context = {
        'products': products
    }
    return render(request, 'core/frontpage.html', context)

def about(request):
    return render(request, 'core/about.html')

multivendor/core/templates/core/about.html
{% extends 'base.html' %}


{% block title %}About{% endblock title %}


{% block content %}
    <h1>About</h1>
{% endblock content %}
    
    

multivendor/core/templates/core/frontpage.html
{% extends 'base.html' %}


{% block title %}Welcome{% endblock title %}
    

{% block content %}
     
     {% include 'store/partials/products.html' %}
      
{% endblock content %}

multivendor/core/templates/core/menu.html
{% for category in categories %}
    <a href="{% url 'category_detail' category.slug %}" class="text-white">{{ category.title }}</a>
{% endfor %}

<a href="{% url 'core:about' %}" class="text-white">About</a>


    